### ISSUE TITLE
You want sound?  Do it yourself

### ISSUE THREAD

**Issue by Brock17** [Brock17/unity-project#16]
Once you've learned the ropes of Unity,
- Replace the <code>atmosphere.wav</code> file, located in the <code>Assets/</code> folder, with something more appropriate... Ideally, a sound that wasn't recorded in  European city.
- Add some sound effects for walking.  It doesn't have to sound pretty, we just need a placeholder for now.  Make the file play only when the player is walking or sprinting.

Also, it's not like I'm running the show.  I founded the project, but you can issue me tickets if you want me to do something.  :smiley:

**Comment by Waffeey** [comment]
I'll see what I can find online for royalty free atmospheric sounds so we don't get sued!

**Comment by Brock17** [comment]
:ok_hand:

**Comment by Brock17** [comment]
You could also record yourself walking on some grass if you want to go all the way.  :laughing:

**Comment by Waffeey** [comment]
Yeah if you can implement it with the walking and sprinting events

**Comment by Brock17** [comment]
Of course you can.

**Comment by Kmonk222** [comment]
LMAO go hardcore on those walking sounds

**Comment by Brock17** [comment]
We're all counting on you for hardcore walking sounds, Tanner.

**Comment by Waffeey** [comment]
You won't be disappointed I'll find some prestine grass

**Comment by Brock17** [comment]
:grapes: I couldn't find an emoticon of grass, so here's some GRApes instead.

**Comment by Kmonk222** [comment]
LMAO

**Comment by Brock17** [comment]
We also need an atmosphere sound too.  :bird: :palm_tree: :bug: :deciduous_tree:  :evergreen_tree: :whale: :christmas_tree:

**Comment by Waffeey** [comment]
I've finished my recordings by alas they are in MPEG-4 codec and not a .wav file, will i need to convert? I'm also looking for a sound playing event to call the the sounds.

**Comment by Brock17** [comment]
MPEG-type files should be totally okay.  May be less in quality, but it's good for now.

**Comment by Brock17** [comment]
We shan't be picky.

**Comment by Waffeey** [comment]
Sweet, getting git set up on the windows right now

**Comment by Waffeey** [comment]
I have actually got it working! Okay now to find out how to actually code this... I have ambient sounds, A minecraft injury sound (For later use), walking/running on grass and stone, and a low stamina out-of-breath sound.

**Comment by Waffeey** [comment]
I have all the other sounds but I will be just changing the ambient sounds for now cause I just found some amazing ambient mixer websites and composed my own sounds perfect for the project w00t.

**Comment by Brock17** [comment]
Sounds good.

**Comment by Waffeey** [comment]
Taking awhile cause im converting to .wav just to be more seamless.

**Comment by Waffeey** [comment]
Yeeeah just replacing the atmosphere.wav doesn't exactly work haha

**Comment by Brock17** [comment]
How does it not work?

**Comment by Waffeey** [comment]
Something to do with the atmosphere.wav.meta file but I can see anything I need to change within it.

**Comment by Brock17** [comment]
Try adding the new atmosphere file and then removing the old one.

**Comment by Waffeey** [comment]
It doesn't crash either so imma push my changes here real quick for you to checkout cause it only has the new .wav file but the old atmosphere sounds play in game.

**Comment by Brock17** [comment]
Lol okay.

**Comment by Waffeey** [comment]
I made sure not too in case you ran it and it broke or something, you can clone it from my branch right?

**Comment by Brock17** [comment]
Yes, I can pull from your specific branch without merging to master.  I'm trying to find your new atmosphere file, but I can't find it anywhere.  I even checked your <code>Sounds/</code> folders, but I didn't find any atmospheric sounds.

**Comment by Waffeey** [comment]
I didn't put the atmosphere.wav file in the sounds folder because it has been converted to a WAV for Unity and the ones in Sounds/ are still MPEG-4, I went right ahead and put it in where it was before, that's why you can't find it lol compare the two between the original on master.

**Comment by Waffeey** [comment]
How did you did that magical grey text around "Sounds/"?

**Comment by Brock17** [comment]
"<code> </code>"  minus the quotes.  

Ex.  "<code>Hello</code>
<code>Hello</code>

**Comment by Brock17** [comment]
If this ticket is giving you a hard time, I could always complete it and then you could do something else.  :smile:

**Comment by Waffeey** [comment]
Merge my pull request so you have the files and you can get them to work I gotta get off xD
Good start to the project today!

**Comment by Brock17** [comment]
All done and done, buddy.  I'll work on it and see what the ISSUE is.  Progress is better than no progress.  I'll release a new alpha version once everything has been completed.
