### ISSUE TITLE
Create an iOS and Linux build

### ISSUE THREAD

**Issue by Brock17** [Brock17/unity-project#18]
In order for this project to be available on platforms other than just Windows, we need to create builds for several OS's.
- Build iOS, Linux, and Android (cause why not?) version of the game.

**Comment by Kmonk222** [comment]
WHAAAAAA? Wouldn't we do that upon completion? That way every update would need to be applied to all platforms.

**Comment by Brock17** [comment]
I'm going to make builds of various platforms upon major game updates, not patches.

**Comment by Brock17** [comment]
We cant make a platform-wide update, since we don't know if it'll be a released on Steam or Origin, per se.
