### ISSUE TITLE
Transfer runningOnGrass.m4a into the sprinting event

### ISSUE THREAD

**Issue by Waffeey** [Brock17/unity-project#26]
Not important now since Unity 5 was just release but in the future.. yeah.

**Comment by Waffeey** [comment]
-oh you can't assign two people to an issue? that's right.

**Comment by Brock17** [comment]
Unfortunately you have to make two tickets for different people.  I wish GitHub would make an update to where they could assign two+ people the same ticket.  :disappointed:
