### ISSUE TITLE
Learn stuff

### ISSUE THREAD

**Issue by Brock17** [Brock17/unity-project#8]
- Go learn some basic Unity stuffs.  Comment on this ticket when you think you've learned enough to actually work on the master project.  (It won't take too long to "learn enough", especially since this project was created not even a week ago...)

**Comment by Waffeey** [comment]
I'll dive into unity this week if i have time after school, which I should. I can record some sweet zombie sounds and other sounds and see how to import them.

**Comment by Brock17** [comment]
Sounds good.  Zombie sounds aren't exactly what we're going for yet, since AI is complicated right now.  Looks for other nature sounds, like grass and trees and walking, etc.

**Comment by Brock17** [comment]
Closing this issue.  I will write you a new one with actual instructions.
